USE TINAPP;

CREATE TABLE USERS(
	ID			INT NOT NULL AUTO_INCREMENT,
    USERNAME 	VARCHAR(200) NOT NULL,
    PASSWORD 	VARCHAR(200) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE TINA(
	ID 			INT NOT NULL AUTO_INCREMENT,
    ID_USER		INT NOT NULL,
    MAC_ADDRESS VARCHAR(200),
    NAME		VARCHAR(200),
    HEIGHT		DOUBLE,
    CONSTRAINT PK_TINA PRIMARY KEY (ID),
    CONSTRAINT FK_TINA FOREIGN KEY (ID_USER) REFERENCES USERS(ID)
);

CREATE TABLE WEEKS(
	ID			INT NOT NULL AUTO_INCREMENT,
    ID_TINA		INT NOT NULL,
    INIT_DAY	INT NOT NULL,
    END_DAY		INT NOT NULL,
    MONTH		INT NOT NULL,
    CONSTRAINT PK_WEEK PRIMARY KEY (ID),
    CONSTRAINT FK_WEEK FOREIGN KEY (ID_TINA) REFERENCES TINA(ID)
);

CREATE TABLE DAYS(
	ID			INT NOT NULL AUTO_INCREMENT,
    ID_WEEK		INT NOT NULL,
    DAY			INT NOT NULL,
    CONSUMPTION	INT NOT NULL,
    CONSTRAINT PK_DAY PRIMARY KEY(ID),
    CONSTRAINT FK_DAY FOREIGN KEY (ID_WEEK) REFERENCES WEEKS(ID)
);